//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 12/13/2018 10:17:39 PM
namespace MiddleEgyptianDictionaryModel
{
    
    /// <summary>
    /// There are no comments for MiddleEgyptianDictionaryEntities in the schema.
    /// </summary>
    public partial class MiddleEgyptianDictionaryEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new MiddleEgyptianDictionaryEntities object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public MiddleEgyptianDictionaryEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Dictionaries in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Dictionary> Dictionaries
        {
            get
            {
                if ((this._Dictionaries == null))
                {
                    this._Dictionaries = base.CreateQuery<Dictionary>("Dictionaries");
                }
                return this._Dictionaries;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Dictionary> _Dictionaries;
        /// <summary>
        /// There are no comments for MetadataEntries in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<MetadataEntry> MetadataEntries
        {
            get
            {
                if ((this._MetadataEntries == null))
                {
                    this._MetadataEntries = base.CreateQuery<MetadataEntry>("MetadataEntries");
                }
                return this._MetadataEntries;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<MetadataEntry> _MetadataEntries;
        /// <summary>
        /// There are no comments for Translations in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Translation> Translations
        {
            get
            {
                if ((this._Translations == null))
                {
                    this._Translations = base.CreateQuery<Translation>("Translations");
                }
                return this._Translations;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Translation> _Translations;
        /// <summary>
        /// There are no comments for UnicodeMaps in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<UnicodeMap> UnicodeMaps
        {
            get
            {
                if ((this._UnicodeMaps == null))
                {
                    this._UnicodeMaps = base.CreateQuery<UnicodeMap>("UnicodeMaps");
                }
                return this._UnicodeMaps;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<UnicodeMap> _UnicodeMaps;
        /// <summary>
        /// There are no comments for Dictionaries in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDictionaries(Dictionary dictionary)
        {
            base.AddObject("Dictionaries", dictionary);
        }
        /// <summary>
        /// There are no comments for MetadataEntries in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMetadataEntries(MetadataEntry metadataEntry)
        {
            base.AddObject("MetadataEntries", metadataEntry);
        }
        /// <summary>
        /// There are no comments for Translations in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTranslations(Translation translation)
        {
            base.AddObject("Translations", translation);
        }
        /// <summary>
        /// There are no comments for UnicodeMaps in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToUnicodeMaps(UnicodeMap unicodeMap)
        {
            base.AddObject("UnicodeMaps", unicodeMap);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"MiddleEgyptianDictionaryModel\" xmlns=\"http://schemas.microsoft.com/ad" +
                "o/2009/11/edm\"><EntityType Name=\"Dictionary\"><Key><PropertyRef Name=\"entryId\" />" +
                "</Key><Property Name=\"entryId\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGenerat" +
                "edPattern=\"Identity\" xmlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/anno" +
                "tation\" /><Property Name=\"transliteration\" Type=\"Edm.String\" Nullable=\"false\" Ma" +
                "xLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"gardinerSigns" +
                "\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"Max\" FixedLength=\"false\" Unicode" +
                "=\"true\" /><NavigationProperty Name=\"Translations\" Relationship=\"MiddleEgyptianDi" +
                "ctionaryModel.FK_DictionaryEntryTranslation\" ToRole=\"Translations\" FromRole=\"Dic" +
                "tionary\" /></EntityType><EntityType Name=\"MetadataEntry\"><Key><PropertyRef Name=" +
                "\"metadataId\" /></Key><Property Name=\"metadataId\" Type=\"Edm.Int32\" Nullable=\"fals" +
                "e\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http://schemas.microsoft.com/ad" +
                "o/2009/02/edm/annotation\" /><Property Name=\"partOfSpeech\" Type=\"Edm.String\" MaxL" +
                "ength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"dictionaryName\"" +
                " Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Translation_translationId\" " +
                "Type=\"Edm.Int32\" Nullable=\"false\" /><NavigationProperty Name=\"Translation\" Relat" +
                "ionship=\"MiddleEgyptianDictionaryModel.FK_TranslationMetadata\" ToRole=\"Translati" +
                "ons\" FromRole=\"MetadataEntries\" /></EntityType><EntityType Name=\"Translation\"><K" +
                "ey><PropertyRef Name=\"translationId\" /></Key><Property Name=\"translationId\" Type" +
                "=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http" +
                "://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"translati" +
                "on1\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"Max\" FixedLength=\"false\" Unic" +
                "ode=\"true\" /><Property Name=\"DictionaryEntry_entryId\" Type=\"Edm.Int32\" Nullable=" +
                "\"false\" /><NavigationProperty Name=\"Dictionary\" Relationship=\"MiddleEgyptianDict" +
                "ionaryModel.FK_DictionaryEntryTranslation\" ToRole=\"Dictionary\" FromRole=\"Transla" +
                "tions\" /><NavigationProperty Name=\"MetadataEntries\" Relationship=\"MiddleEgyptian" +
                "DictionaryModel.FK_TranslationMetadata\" ToRole=\"MetadataEntries\" FromRole=\"Trans" +
                "lations\" /></EntityType><EntityType Name=\"UnicodeMap\"><Key><PropertyRef Name=\"id" +
                "\" /></Key><Property Name=\"id\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGenerate" +
                "dPattern=\"Identity\" xmlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annot" +
                "ation\" /><Property Name=\"gardinerName\" Type=\"Edm.String\" Nullable=\"false\" MaxLen" +
                "gth=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"unicode\" Type=\"Ed" +
                "m.String\" Nullable=\"false\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" />" +
                "</EntityType><Association Name=\"FK_DictionaryEntryTranslation\"><End Type=\"Middle" +
                "EgyptianDictionaryModel.Dictionary\" Role=\"Dictionary\" Multiplicity=\"1\" /><End Ty" +
                "pe=\"MiddleEgyptianDictionaryModel.Translation\" Role=\"Translations\" Multiplicity=" +
                "\"*\" /><ReferentialConstraint><Principal Role=\"Dictionary\"><PropertyRef Name=\"ent" +
                "ryId\" /></Principal><Dependent Role=\"Translations\"><PropertyRef Name=\"Dictionary" +
                "Entry_entryId\" /></Dependent></ReferentialConstraint></Association><Association " +
                "Name=\"FK_TranslationMetadata\"><End Type=\"MiddleEgyptianDictionaryModel.Translati" +
                "on\" Role=\"Translations\" Multiplicity=\"1\" /><End Type=\"MiddleEgyptianDictionaryMo" +
                "del.MetadataEntry\" Role=\"MetadataEntries\" Multiplicity=\"*\" /><ReferentialConstra" +
                "int><Principal Role=\"Translations\"><PropertyRef Name=\"translationId\" /></Princip" +
                "al><Dependent Role=\"MetadataEntries\"><PropertyRef Name=\"Translation_translationI" +
                "d\" /></Dependent></ReferentialConstraint></Association></Schema><Schema Namespac" +
                "e=\"MEDWebApp\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/edm\"><EntityContai" +
                "ner Name=\"MiddleEgyptianDictionaryEntities\" m:IsDefaultEntityContainer=\"true\"><E" +
                "ntitySet Name=\"Dictionaries\" EntityType=\"MiddleEgyptianDictionaryModel.Dictionar" +
                "y\" /><EntitySet Name=\"MetadataEntries\" EntityType=\"MiddleEgyptianDictionaryModel" +
                ".MetadataEntry\" /><EntitySet Name=\"Translations\" EntityType=\"MiddleEgyptianDicti" +
                "onaryModel.Translation\" /><EntitySet Name=\"UnicodeMaps\" EntityType=\"MiddleEgypti" +
                "anDictionaryModel.UnicodeMap\" /><AssociationSet Name=\"FK_DictionaryEntryTranslat" +
                "ion\" Association=\"MiddleEgyptianDictionaryModel.FK_DictionaryEntryTranslation\"><" +
                "End Role=\"Dictionary\" EntitySet=\"Dictionaries\" /><End Role=\"Translations\" Entity" +
                "Set=\"Translations\" /></AssociationSet><AssociationSet Name=\"FK_TranslationMetada" +
                "ta\" Association=\"MiddleEgyptianDictionaryModel.FK_TranslationMetadata\"><End Role" +
                "=\"MetadataEntries\" EntitySet=\"MetadataEntries\" /><End Role=\"Translations\" Entity" +
                "Set=\"Translations\" /></AssociationSet></EntityContainer></Schema></edmx:DataServ" +
                "ices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for MiddleEgyptianDictionaryModel.Dictionary in the schema.
    /// </summary>
    /// <KeyProperties>
    /// entryId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Dictionaries")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("entryId")]
    public partial class Dictionary : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Dictionary object.
        /// </summary>
        /// <param name="entryId">Initial value of entryId.</param>
        /// <param name="transliteration">Initial value of transliteration.</param>
        /// <param name="gardinerSigns">Initial value of gardinerSigns.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Dictionary CreateDictionary(int entryId, string transliteration, string gardinerSigns)
        {
            Dictionary dictionary = new Dictionary();
            dictionary.entryId = entryId;
            dictionary.transliteration = transliteration;
            dictionary.gardinerSigns = gardinerSigns;
            return dictionary;
        }
        /// <summary>
        /// There are no comments for Property entryId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int entryId
        {
            get
            {
                return this._entryId;
            }
            set
            {
                this.OnentryIdChanging(value);
                this._entryId = value;
                this.OnentryIdChanged();
                this.OnPropertyChanged("entryId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _entryId;
        partial void OnentryIdChanging(int value);
        partial void OnentryIdChanged();
        /// <summary>
        /// There are no comments for Property transliteration in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string transliteration
        {
            get
            {
                return this._transliteration;
            }
            set
            {
                this.OntransliterationChanging(value);
                this._transliteration = value;
                this.OntransliterationChanged();
                this.OnPropertyChanged("transliteration");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _transliteration;
        partial void OntransliterationChanging(string value);
        partial void OntransliterationChanged();
        /// <summary>
        /// There are no comments for Property gardinerSigns in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string gardinerSigns
        {
            get
            {
                return this._gardinerSigns;
            }
            set
            {
                this.OngardinerSignsChanging(value);
                this._gardinerSigns = value;
                this.OngardinerSignsChanged();
                this.OnPropertyChanged("gardinerSigns");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _gardinerSigns;
        partial void OngardinerSignsChanging(string value);
        partial void OngardinerSignsChanged();
        /// <summary>
        /// There are no comments for Translations in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Translation> Translations
        {
            get
            {
                return this._Translations;
            }
            set
            {
                this._Translations = value;
                this.OnPropertyChanged("Translations");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Translation> _Translations = new global::System.Data.Services.Client.DataServiceCollection<Translation>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for MiddleEgyptianDictionaryModel.MetadataEntry in the schema.
    /// </summary>
    /// <KeyProperties>
    /// metadataId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("MetadataEntries")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("metadataId")]
    public partial class MetadataEntry : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new MetadataEntry object.
        /// </summary>
        /// <param name="metadataId">Initial value of metadataId.</param>
        /// <param name="dictionaryName">Initial value of dictionaryName.</param>
        /// <param name="translation_translationId">Initial value of Translation_translationId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static MetadataEntry CreateMetadataEntry(int metadataId, int dictionaryName, int translation_translationId)
        {
            MetadataEntry metadataEntry = new MetadataEntry();
            metadataEntry.metadataId = metadataId;
            metadataEntry.dictionaryName = dictionaryName;
            metadataEntry.Translation_translationId = translation_translationId;
            return metadataEntry;
        }
        /// <summary>
        /// There are no comments for Property metadataId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int metadataId
        {
            get
            {
                return this._metadataId;
            }
            set
            {
                this.OnmetadataIdChanging(value);
                this._metadataId = value;
                this.OnmetadataIdChanged();
                this.OnPropertyChanged("metadataId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _metadataId;
        partial void OnmetadataIdChanging(int value);
        partial void OnmetadataIdChanged();
        /// <summary>
        /// There are no comments for Property partOfSpeech in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string partOfSpeech
        {
            get
            {
                return this._partOfSpeech;
            }
            set
            {
                this.OnpartOfSpeechChanging(value);
                this._partOfSpeech = value;
                this.OnpartOfSpeechChanged();
                this.OnPropertyChanged("partOfSpeech");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _partOfSpeech;
        partial void OnpartOfSpeechChanging(string value);
        partial void OnpartOfSpeechChanged();
        /// <summary>
        /// There are no comments for Property dictionaryName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int dictionaryName
        {
            get
            {
                return this._dictionaryName;
            }
            set
            {
                this.OndictionaryNameChanging(value);
                this._dictionaryName = value;
                this.OndictionaryNameChanged();
                this.OnPropertyChanged("dictionaryName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _dictionaryName;
        partial void OndictionaryNameChanging(int value);
        partial void OndictionaryNameChanged();
        /// <summary>
        /// There are no comments for Property Translation_translationId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Translation_translationId
        {
            get
            {
                return this._Translation_translationId;
            }
            set
            {
                this.OnTranslation_translationIdChanging(value);
                this._Translation_translationId = value;
                this.OnTranslation_translationIdChanged();
                this.OnPropertyChanged("Translation_translationId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Translation_translationId;
        partial void OnTranslation_translationIdChanging(int value);
        partial void OnTranslation_translationIdChanged();
        /// <summary>
        /// There are no comments for Translation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Translation Translation
        {
            get
            {
                return this._Translation;
            }
            set
            {
                this._Translation = value;
                this.OnPropertyChanged("Translation");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Translation _Translation;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for MiddleEgyptianDictionaryModel.Translation in the schema.
    /// </summary>
    /// <KeyProperties>
    /// translationId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Translations")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("translationId")]
    public partial class Translation : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Translation object.
        /// </summary>
        /// <param name="translationId">Initial value of translationId.</param>
        /// <param name="translation1">Initial value of translation1.</param>
        /// <param name="dictionaryEntry_entryId">Initial value of DictionaryEntry_entryId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Translation CreateTranslation(int translationId, string translation1, int dictionaryEntry_entryId)
        {
            Translation translation = new Translation();
            translation.translationId = translationId;
            translation.translation1 = translation1;
            translation.DictionaryEntry_entryId = dictionaryEntry_entryId;
            return translation;
        }
        /// <summary>
        /// There are no comments for Property translationId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int translationId
        {
            get
            {
                return this._translationId;
            }
            set
            {
                this.OntranslationIdChanging(value);
                this._translationId = value;
                this.OntranslationIdChanged();
                this.OnPropertyChanged("translationId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _translationId;
        partial void OntranslationIdChanging(int value);
        partial void OntranslationIdChanged();
        /// <summary>
        /// There are no comments for Property translation1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string translation1
        {
            get
            {
                return this._translation1;
            }
            set
            {
                this.Ontranslation1Changing(value);
                this._translation1 = value;
                this.Ontranslation1Changed();
                this.OnPropertyChanged("translation1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _translation1;
        partial void Ontranslation1Changing(string value);
        partial void Ontranslation1Changed();
        /// <summary>
        /// There are no comments for Property DictionaryEntry_entryId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int DictionaryEntry_entryId
        {
            get
            {
                return this._DictionaryEntry_entryId;
            }
            set
            {
                this.OnDictionaryEntry_entryIdChanging(value);
                this._DictionaryEntry_entryId = value;
                this.OnDictionaryEntry_entryIdChanged();
                this.OnPropertyChanged("DictionaryEntry_entryId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _DictionaryEntry_entryId;
        partial void OnDictionaryEntry_entryIdChanging(int value);
        partial void OnDictionaryEntry_entryIdChanged();
        /// <summary>
        /// There are no comments for Dictionary in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Dictionary Dictionary
        {
            get
            {
                return this._Dictionary;
            }
            set
            {
                this._Dictionary = value;
                this.OnPropertyChanged("Dictionary");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Dictionary _Dictionary;
        /// <summary>
        /// There are no comments for MetadataEntries in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<MetadataEntry> MetadataEntries
        {
            get
            {
                return this._MetadataEntries;
            }
            set
            {
                this._MetadataEntries = value;
                this.OnPropertyChanged("MetadataEntries");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<MetadataEntry> _MetadataEntries = new global::System.Data.Services.Client.DataServiceCollection<MetadataEntry>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for MiddleEgyptianDictionaryModel.UnicodeMap in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("UnicodeMaps")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class UnicodeMap : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new UnicodeMap object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        /// <param name="gardinerName">Initial value of gardinerName.</param>
        /// <param name="unicode">Initial value of unicode.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static UnicodeMap CreateUnicodeMap(int ID, string gardinerName, string unicode)
        {
            UnicodeMap unicodeMap = new UnicodeMap();
            unicodeMap.id = ID;
            unicodeMap.gardinerName = gardinerName;
            unicodeMap.unicode = unicode;
            return unicodeMap;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property gardinerName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string gardinerName
        {
            get
            {
                return this._gardinerName;
            }
            set
            {
                this.OngardinerNameChanging(value);
                this._gardinerName = value;
                this.OngardinerNameChanged();
                this.OnPropertyChanged("gardinerName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _gardinerName;
        partial void OngardinerNameChanging(string value);
        partial void OngardinerNameChanged();
        /// <summary>
        /// There are no comments for Property unicode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string unicode
        {
            get
            {
                return this._unicode;
            }
            set
            {
                this.OnunicodeChanging(value);
                this._unicode = value;
                this.OnunicodeChanged();
                this.OnPropertyChanged("unicode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _unicode;
        partial void OnunicodeChanging(string value);
        partial void OnunicodeChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
